[workspace]
members = [
    "proxy",
    "intra-jwt",
    "certman",
    "env_utils",
    "gaia/gaia-backend",
    "gaia/gaia-backend/migration",
    "gaia/gaia-backend/entity",
    "router",
    "router/migration",
    "router/entity",
]
