version: '3.8'

services:
  proxy:
    build:
      context: .
      dockerfile: proxy/Dockerfile
    image: ct2-proxy
    ports:
      - "8443:8443"
      - "8080:8080"
    environment:
      - JWT_PEM=/certs/jwt-key.pem
      - CA_CERT=/certs/rootCA.pem
      - SERVER_CERT=/certs/server-cert.pem
      - SERVER_KEY=/certs/server-key.pem
    volumes:
      - ./data/certs:/certs
  gaia-backend:
    build:
      context: .
      dockerfile: gaia/gaia-backend/Dockerfile
    image: ct2-gaia-backend
    ports:
      - "8081:8081"
    environment:
      - "DB_URI=sqlite:///data/db.db"
      - "JWT_PEM_LOC=/certs/jwt-key.pem"
      - "PASETO_KEY=12345679801234567980123456798012"
    volumes:
      - ./data/gaia-backend:/data
      - ./data/certs:/certs
