unstable_features = true


enum_discrim_align_threshold = 20
struct_field_align_threshold = 20

condense_wildcard_suffixes = true
fn_single_line = true
format_code_in_doc_comments = true
hex_literal_case = "Lower"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
imports_granularity = "Crate"
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true

normalize_comments = true
normalize_doc_attributes = true

reorder_impl_items = true
group_imports = "StdExternalCrate"

wrap_comments = true
comment_width = 100
